version: "3"
services:
  service1:
    image: fvmapo/service1-image
    ports:
      - "8001:8001"
    depends_on:
      - service2
    networks:
      - fvmapo_default
  service2:
    image: fvmapo/service2-image
    ports:
      - "3000"
    networks:
      - fvmapo_default

networks:
  fvmapo_default:
    external: true